{{- if .Values.service.external.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mosquitto.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  secretName: {{ default (printf "%s-tls" (include "mosquitto.fullname" .)) .Values.service.external.tls.secretName }}

  commonName: {{ default (printf "%s.%s" (include "mosquitto.fullname" .) .Release.Namespace) .Values.service.external.tls.commonName }}

  dnsNames:
    {{- with .Values.service.external.tls.dnsNames }}
      {{- toYaml . | nindent 4 }}
    {{- else }}
      - {{ include "mosquitto.fullname" . }}.{{ .Release.Namespace }}
    {{- end }}

  issuerRef:
    kind: {{ default "ClusterIssuer" .Values.service.external.tls.issuer.kind }}
    name: {{ default "internal-ca" .Values.service.external.tls.issuer.name }}
{{- end }}
