{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-secret
type: Opaque
data:
  passwords.txt: {{ .Values.mosquitto.passwordsTxt | b64enc | quote }}
{{- end }}